<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Society;
use App\Models\SubscriptionPlan;

class SocietySeeder extends Seeder
{
    public function run(): void
    {
        $plans = SubscriptionPlan::all();

        $societies = [
            [
                'name' => 'Green Valley CHS',
                'registration_number' => 'MUM/HSV/2015/01234',
                'prefix' => 'GRN',
                'society_type_id' => 1,
                'registration_date' => '2015-03-15',
                'pan_number' => 'AAATG1234F',
                'flats_count' => 240,
                'shops_count' => 10,
                'offices_count' => 6,
                'address_line_1' => 'Plot No. 45, Sector 10',
                'city' => 'Navi Mumbai',
                'state' => 'Maharashtra',
                'pincode' => '400703',
                'primary_email' => 'contact@greenvalley.in',
                'primary_mobile' => '+91 98765 43210',
                'chairman_name' => 'Mr. Rajesh Sharma',
                'secretary_name' => 'Ms. Anita Desai',
                'treasurer_name' => 'Mr. Vivek Mehta',
                'subscription_plan_id' => $plans[2]->id,
                'subscription_start_date' => '2024-01-01',
                'subscription_end_date' => '2026-12-31',
                'subscription_status' => 'active',
                'status' => 'active',
            ],
            [
                'name' => 'Shree Sai Residency',
                'registration_number' => 'MUM/HSR/2018/02345',
                'prefix' => 'SSR',
                'society_type_id' => 1,
                'registration_date' => '2018-07-20',
                'pan_number' => 'AAASS5678G',
                'flats_count' => 160,
                'shops_count' => 12,
                'offices_count' => 8,
                'address_line_1' => 'Sai Nagar, Near DMart',
                'city' => 'Panvel',
                'state' => 'Maharashtra',
                'pincode' => '410206',
                'primary_email' => 'info@shreesairesidency.in',
                'primary_mobile' => '+91 97654 32109',
                'chairman_name' => 'Mr. Ganesh Patil',
                'secretary_name' => 'Mrs. Sunita Rao',
                'treasurer_name' => 'Mr. Mohan Gupta',
                'subscription_plan_id' => $plans[1]->id,
                'subscription_start_date' => '2024-02-10',
                'subscription_end_date' => '2027-03-15',
                'subscription_status' => 'active',
                'status' => 'active',
            ],
            [
                'name' => 'Skyline Heights',
                'registration_number' => 'MUM/HSS/2016/03456',
                'prefix' => 'SKY',
                'society_type_id' => 3,
                'registration_date' => '2016-11-05',
                'pan_number' => 'AAASK9012H',
                'flats_count' => 300,
                'shops_count' => 8,
                'offices_count' => 4,
                'address_line_1' => 'Pokhran Road No. 2',
                'city' => 'Thane',
                'state' => 'Maharashtra',
                'pincode' => '400610',
                'primary_email' => 'admin@skylineheights.in',
                'primary_mobile' => '+91 90234 56789',
                'chairman_name' => 'Mr. Arjun Khanna',
                'secretary_name' => 'Ms. Priya Nair',
                'treasurer_name' => 'Mr. Sanjay Joshi',
                'subscription_plan_id' => $plans[2]->id,
                'subscription_start_date' => '2024-03-01',
                'subscription_end_date' => '2026-07-20',
                'subscription_status' => 'expiring_soon',
                'status' => 'active',
            ],
            [
                'name' => 'Sunrise Apartments',
                'registration_number' => 'MUM/HSA/2019/04567',
                'prefix' => 'SUN',
                'society_type_id' => 1,
                'registration_date' => '2019-04-12',
                'pan_number' => 'AAASU3456I',
                'flats_count' => 80,
                'shops_count' => 12,
                'offices_count' => 6,
                'address_line_1' => 'Kharghar Sector 20',
                'city' => 'Kharghar',
                'state' => 'Maharashtra',
                'pincode' => '410210',
                'primary_email' => 'sunrise@apartments.in',
                'primary_mobile' => '+91 98987 65432',
                'chairman_name' => 'Mr. Deepak Verma',
                'secretary_name' => 'Mrs. Lata Sharma',
                'treasurer_name' => 'Mr. Nitin Patel',
                'subscription_plan_id' => $plans[0]->id,
                'subscription_start_date' => '2023-06-01',
                'subscription_end_date' => '2026-06-10',
                'subscription_status' => 'expired',
                'status' => 'inactive',
            ],
            [
                'name' => 'Silver Oak Society',
                'registration_number' => 'MUM/HSL/2017/05678',
                'prefix' => 'SIL',
                'society_type_id' => 1,
                'registration_date' => '2017-09-25',
                'pan_number' => 'AAASL7890J',
                'flats_count' => 120,
                'shops_count' => 14,
                'offices_count' => 6,
                'address_line_1' => 'Ulwe Sector 19',
                'city' => 'Ulwe',
                'state' => 'Maharashtra',
                'pincode' => '410206',
                'primary_email' => 'silveroak@society.in',
                'primary_mobile' => '+91 99876 54321',
                'chairman_name' => 'Mr. Ravi Kumar',
                'secretary_name' => 'Ms. Meera Iyer',
                'treasurer_name' => 'Mr. Anil Shah',
                'subscription_plan_id' => $plans[1]->id,
                'subscription_start_date' => '2024-05-12',
                'subscription_end_date' => '2027-02-05',
                'subscription_status' => 'active',
                'status' => 'active',
            ],
            [
                'name' => 'Lotus Residency',
                'registration_number' => 'MUM/HSLR/2020/06789',
                'prefix' => 'LOT',
                'society_type_id' => 2,
                'registration_date' => '2020-01-18',
                'pan_number' => 'AAALO1234K',
                'flats_count' => 150,
                'shops_count' => 10,
                'offices_count' => 5,
                'address_line_1' => 'Kopar Khairane Sector 8',
                'city' => 'Navi Mumbai',
                'state' => 'Maharashtra',
                'pincode' => '400709',
                'primary_email' => 'lotus@residency.in',
                'primary_mobile' => '+91 91567 89012',
                'chairman_name' => 'Mr. Suresh Menon',
                'secretary_name' => 'Mrs. Kavita Das',
                'treasurer_name' => 'Mr. Prakash Reddy',
                'subscription_plan_id' => $plans[1]->id,
                'subscription_start_date' => '2024-05-18',
                'subscription_end_date' => '2027-01-18',
                'subscription_status' => 'active',
                'status' => 'active',
            ],
            [
                'name' => 'Harmony Enclave',
                'registration_number' => 'MUM/HSH/2014/07890',
                'prefix' => 'HAR',
                'society_type_id' => 1,
                'registration_date' => '2014-06-30',
                'pan_number' => 'AAAHM5678L',
                'flats_count' => 200,
                'shops_count' => 12,
                'offices_count' => 8,
                'address_line_1' => 'Belapur CBD Sector 11',
                'city' => 'Belapur',
                'state' => 'Maharashtra',
                'pincode' => '400614',
                'primary_email' => 'contact@harmonyenclave.in',
                'primary_mobile' => '+91 90012 34567',
                'chairman_name' => 'Mr. Vikram Singh',
                'secretary_name' => 'Ms. Ananya Bose',
                'treasurer_name' => 'Mr. Ramesh Yadav',
                'subscription_plan_id' => $plans[2]->id,
                'subscription_start_date' => '2024-06-22',
                'subscription_end_date' => '2026-08-01',
                'subscription_status' => 'expiring_soon',
                'status' => 'active',
            ],
            [
                'name' => 'Maple Leaf CHS',
                'registration_number' => 'MUM/HSML/2021/08901',
                'prefix' => 'MAP',
                'society_type_id' => 1,
                'registration_date' => '2021-06-30',
                'pan_number' => 'AAAML9012M',
                'flats_count' => 60,
                'shops_count' => 10,
                'offices_count' => 5,
                'address_line_1' => 'Vashi Sector 17',
                'city' => 'Vashi',
                'state' => 'Maharashtra',
                'pincode' => '400703',
                'primary_email' => 'mapleleaf@chs.in',
                'primary_mobile' => '+91 91234 56789',
                'chairman_name' => 'Mr. Ashok Mishra',
                'secretary_name' => 'Mrs. Pooja Kapoor',
                'treasurer_name' => 'Mr. Rahul Jain',
                'subscription_plan_id' => $plans[0]->id,
                'subscription_start_date' => '2024-06-30',
                'subscription_end_date' => '2026-05-25',
                'subscription_status' => 'expired',
                'status' => 'inactive',
            ],
        ];

        foreach ($societies as $society) {
            Society::create($society);
        }
    }
}
